<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1
| Term       | Brief description |
|------------|-------------------|
| Subsetting |Adding certain elements into the array *No, its toselect a subset of the data in a list or array*|
| Indexing   |Positioning of the individual elements within the array *No, its to pick a single element, the act of selecting one element*|
| Slicing    |Removing certain elements from the array *No, it means selecting a range of elements*|
| Masking    |Prevents a certain group of elements from being called *its subseting to ask NumPy to show only those that are TRUE*|



In [7]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

#print(np_array_2d[:,0]) for checking

np_array_2d = np_array_2d[:,0].astype(int)

#print(np_array_2d) for checking

np_array_2d = np_array_2d % 2

print(np_array_2d)

print(np_array_2d != 0)
mask = np_array_2d !=0
np_array_2d[mask]



[1 1 0 0 1 1 0 0 0 1]
[ True  True False False  True  True False False False  True]


array([1, 1, 1, 1, 1])

## Exercise 3

In [ ]:
p = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

mask1 = p < 50
mask2 = p > 50
mask3 = p == 50

#print(p[mask1])

#print(p[mask2])


p[mask2] = 1


#print(p)
#print(p[mask3])


p[mask3] = 0

print(p)



[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
