<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [7]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array


print(x[0])
print(x[-1])
print(x[0:3])
print(x[1:6])
print(x[1:6:2])
print(x[5:])
print(x[:5])
print(x[5:2:-1])
print(x[::1])



a1
j10
['a1' 'b2' 'c3']
['b2' 'c3' 'd4' 'e5' 'f6']
['b2' 'd4' 'f6']
['f6' 'g7' 'h8' 'i9' 'j10']
['a1' 'b2' 'c3' 'd4' 'e5']
['f6' 'e5' 'd4']
['a1' 'b2' 'c3' 'd4' 'e5' 'f6' 'g7' 'h8' 'i9' 'j10']


## 1.2 Arrays only | Subsetting by masking

In [8]:
import numpy as np
np_array = np.array([1,2,3,4,5,6,7,8,9,10])
my_mask = np_array > 3
print(my_mask)

print(np_array[my_mask])

print(np_array[np_array > 3])

print(np_array[~(np_array > 3)]) # ~ means not 

print(np_array[(np_array > 3) & (np_array < 8)]) # & means and

print(np_array[(np_array < 3) | (np_array > 8)]) # | means or



[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10]
[1 2 3]
[4 5 6 7]
[ 1  2  9 10]


## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [ ]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9,"I"], [10,"J"]]

np_array_2d = np.array(py_list_2d)

print(py_list_2d[3])
print(np_array_2d[3])

print(py_list_2d[3][0])
print(np_array_2d[3,0])

print(py_list_2d[:3])
print(np_array_2d[:3])

print(py_list_2d[:3][0])
print(np_array_2d[:3,0])

print(py_list_2d[3:6][0])
print(np_array_2d[3:6, 0])
print(np_array_2d[:, 0])

[4, 'D']
['4' 'D']
4
4
[[1, 'A'], [2, 'B'], [3, 'C']]
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]
[1, 'A']
['1' '2' '3']
[4, 'D']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


## 1.4 Growing lists

In [18]:
x = [1,2]*5
print(x)

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


In [22]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
print(x)

x=[1]
x+= [2]
x+= [3]
x+= [4]
print(x)

x=[1]
x.append(2)
x.append(3)
x.append(4)
print(x)

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]


In [23]:
x = [1, 2, 3]
x += [4, 5, 6]
print(x)
x=[1, 2, 3]
x.extend([4, 5, 6])
print(x)
x=[1, 2, 3]
x.append([4, 5, 6])
print(x)



[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, [4, 5, 6]]


# Some loose ends

## 1.5 Tuples

In [25]:
a = (1,2,3) #define tuple
print(a[0]) #can access data

#cannot change data:
# a[0]=-1
# a[0] += [10]

1


## 1.6 Be VERY careful when copying

In [26]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

print(y)
print(z)

[1, 2, 3]
[1, 2, 3]


In [28]:
x=[1,2,3]
y =x.copy()
z=x.copy()

print(x)
print(y)

[1, 2, 3]
[1, 2, 3]


## Footnotes